name: exist-db CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
       matrix:
         exist-version: [5.2, release]
         java-version: [8]

    steps:
      # Checkout code
      - uses: actions/checkout@v3
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-        
      
      # Build Expath Package 
      - name: Build Expath Package
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - run: ant 

      - name: Install Bats
        run: sudo apt-get -y install bats
      
      # Deploy Package in Container
      - name: Pull Base Image
        run: docker pull existdb/existdb:${{ matrix.exist-version }}

      - name: Create CI Container
        run: docker create  --name exist-ci -p 8080:8080 existdb/existdb:${{ matrix.exist-version }} 

      - name: Prep CI Container
        run: docker cp ./build/*-dev.xar exist-ci:exist/autodeploy

      - name: Start Exist Container
        run: docker start exist-ci && sleep 30

      # Testing 
      - name: Run Bats Tests
        run: bats --tap test/*.bats
